language: go

before_install:
  - sudo apt-get -qq update
  - sudo apt-get -qq install libreadline-dev

script: 
  - make
#  - make container push-container

go:
  - 1.6

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/c4291c41b02c0ad801e3
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always